name: Build MCU Project

on:
  push:
    branches:
      - main
      - port_hw_v2
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMON_BUILD_CMD: "stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data ./workspace -import ./ExpanderFw"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Docker
        run: |
          docker pull xanderhendriks/stm32cubeide:13.1

      - name: Build Debug
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/expander-mcu/ExpanderFw \
            xanderhendriks/stm32cubeide:13.1 \
            bash -c "${{ env.COMMON_BUILD_CMD }} -cleanBuild ExpanderFw/Debug"

      - name: Build Release
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace/expander-mcu/ExpanderFw \
            xanderhendriks/stm32cubeide:13.1 \
            bash -c "${{ env.COMMON_BUILD_CMD }} -cleanBuild ExpanderFw/Release"

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v3
        with:
          path: |
            expander-mcu/ExpanderFw/Debug/ExpanderFw.hex
            expander-mcu/ExpanderFw/Debug/ExpanderFw.bin
            expander-mcu/ExpanderFw/Debug/ExpanderFw.elf
            expander-mcu/ExpanderFw/Release/ExpanderFw.hex
            expander-mcu/ExpanderFw/Release/ExpanderFw.bin
            expander-mcu/ExpanderFw/Release/ExpanderFw.elf
